app = "airin-project" # Replace with your app name on Fly.io

[build]
  image = "Dockerfile"

[env]
  PORT = "3000" # The port your app listens to (default for Node.js)

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[mounts]
  source = "data"
  destination = "/data" # Optional: Mount for persistent storage (if needed)

[deploy]
  release_command = "npm run build && npm run start" # Adjust based on your app
