app = "airin-project" # Replace with your app name

# Use pre-built Docker image
[build]
  image = "ghcr.io/noname968/airin:latest"

[env]
  PORT = "3000" # Internal app port
  MONGO_INITDB_ROOT_USERNAME = "root"
  MONGO_INITDB_ROOT_PASSWORD = "somePass"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Health checks (optional)
  [services.health_checks]
    path = "/healthz" # Adjust based on your app's endpoint
    interval = "15s"
    timeout = "5s"

# Persistent storage for MongoDB
[[mounts]]
  source = "db_data"
  destination = "/data/db"

# Persistent storage for Redis
[[mounts]]
  source = "redis_cache"
  destination = "/data/cache"

[deploy]
  release_command = "docker-compose up"
